/*
 * Hard guardrails: a generated PreToolUse hook that blocks reads/writes/commands
 * touching guarded paths, plus the deny-rule mirror in settings.json.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { CLAUDE_DIR } = require('./constants');
const { readJsonSafe, rotateBackups } = require('./util');
const { settingsPath } = require('./settings');

// Static PreToolUse hook. Reads its sibling maestro-guardrails.json on every call,
// so list edits apply instantly without touching settings again. Exit 2 = block.
const HOOK_SCRIPT = `#!/usr/bin/env node
// Generated by Maestro - hard guardrails for Claude Code.
// Managed by the Maestro UI; edits here are overwritten on the next Apply.
'use strict';
const fs = require('fs'), path = require('path');
let input = '';
process.stdin.on('data', (d) => { input += d; });
process.stdin.on('end', () => {
  try {
    const evt = JSON.parse(input || '{}');
    const cfg = JSON.parse(fs.readFileSync(path.join(__dirname, 'maestro-guardrails.json'), 'utf8'));
    const tool = evt.tool_name || '';
    const ti = evt.tool_input || {};
    const escRe = (s) => s.replace(/[.+^$()|[\\]{}\\\\]/g, '\\\\$&');
    const globRe = (g) => {
      const body = escRe(String(g).replace(/\\\\/g, '/'))
        .replace(/\\*\\*/g, '\\u0000').replace(/\\*/g, '[^/]*')
        .replace(/\\u0000/g, '.*').replace(/\\?/g, '.');
      return g.includes('/')
        ? new RegExp('(^|/)' + body + '$', 'i')
        : new RegExp('^' + body + '$', 'i');
    };
    const block = (msg) => { process.stderr.write('Maestro guardrail: ' + msg); process.exit(2); };

    const fileTools = { Read: 'file_path', Edit: 'file_path', Write: 'file_path', MultiEdit: 'file_path', NotebookEdit: 'notebook_path' };
    if (fileTools[tool]) {
      const p = String(ti[fileTools[tool]] || '').replace(/\\\\/g, '/');
      for (const g of (cfg.files || [])) {
        const re = globRe(g);
        if (re.test(p) || re.test(path.posix.basename(p))) {
          block('access to "' + p + '" is blocked by rule "' + g + '". Do not retry via other tools.');
        }
      }
    }
    // Search tools are a read path too. "Grep" with output_mode:"content"
    // prints the matching lines of a file it was never allowed to Read, and
    // "Glob" confirms a guarded file exists. Blocking Read alone left both open.
    if (tool === 'Grep' || tool === 'Glob') {
      const cand = (tool === 'Glob' ? [ti.pattern, ti.path] : [ti.path, ti.glob])
        .filter(Boolean).map((s) => String(s).replace(/\\\\/g, '/'));
      for (const g of (cfg.files || [])) {
        const re = globRe(g);
        for (const c of cand) {
          if (re.test(c) || re.test(path.posix.basename(c))) {
            block('searching "' + c + '" is blocked by rule "' + g + '". Do not retry via other tools.');
          }
        }
      }
    }
    if (tool === 'Bash' || tool === 'PowerShell') {
      const cmd = String(ti.command || '');
      const B = '[\\\\s;|&()\`"\\'=]'; // token boundaries incl. quotes/pipes/subshells
      for (const c of (cfg.commands || [])) {
        const re = new RegExp('(^|' + B + ')' + escRe(c).replace(/\\*/g, '\\\\S*') + '($|' + B + ')', 'i');
        if (re.test(cmd)) block('command contains blocked token "' + c + '". Do not retry this in another form.');
      }
      for (const g of (cfg.files || [])) {
        const bare = String(g).replace(/[*?]/g, '').split('/').pop();
        if (bare && bare.length >= 3 && cmd.toLowerCase().includes(bare.toLowerCase())) {
          block('command references guarded file "' + bare + '" (rule "' + g + '").');
        }
      }
    }
    process.exit(0);
  } catch (e) {
    process.exit(0); // fail open: a broken config must not brick every session
  }
});
`;

function guardPaths(scope, dir) {
  const hookDir = scope === 'user' ? path.join(CLAUDE_DIR, 'hooks') : path.join(dir, '.claude', 'hooks');
  return {
    hookDir,
    hookFile: path.join(hookDir, 'maestro-guard.js'),
    cfgFile: path.join(hookDir, 'maestro-guardrails.json'),
    settingsFile: settingsPath(scope, dir),
    hookCmd: scope === 'user'
      ? `node "${path.join(hookDir, 'maestro-guard.js')}"`
      : `node "$CLAUDE_PROJECT_DIR/.claude/hooks/maestro-guard.js"`,
  };
}

function genDenyRules(cfg) {
  const rules = [];
  for (const g of cfg.files || []) rules.push(`Read(${g})`, `Edit(${g})`, `Write(${g})`);
  for (const c of cfg.commands || []) rules.push(`Bash(${c})`, `Bash(${c} *)`);
  return rules;
}

function guardIsRegistered(settings) {
  const pre = settings && settings.hooks && settings.hooks.PreToolUse;
  if (!Array.isArray(pre)) return false;
  return pre.some((m) => (m.hooks || []).some((h) => String(h.command || '').includes('maestro-guard.js')));
}

function applyGuard(body) {
  const { scope, dir } = body;
  if (scope !== 'user' && (!dir || !path.isAbsolute(dir))) throw new Error('project directory required for this scope');
  const gp = guardPaths(scope, dir);
  const cfg = {
    files: (body.files || []).map(String).filter(Boolean),
    commands: (body.commands || []).map(String).filter(Boolean),
    updated: new Date().toISOString(),
  };
  const prev = readJsonSafe(gp.cfgFile) || { files: [], commands: [] };

  fs.mkdirSync(gp.hookDir, { recursive: true });
  fs.writeFileSync(gp.hookFile, HOOK_SCRIPT, { mode: 0o755 });
  fs.writeFileSync(gp.cfgFile, JSON.stringify(cfg, null, 2) + '\n');

  const settings = readJsonSafe(gp.settingsFile) || {};
  settings.hooks = settings.hooks || {};
  settings.hooks.PreToolUse = settings.hooks.PreToolUse || [];
  if (!guardIsRegistered(settings)) {
    settings.hooks.PreToolUse.push({ hooks: [{ type: 'command', command: gp.hookCmd, timeout: 10 }] });
  }

  // Mirror into permission deny rules (defense in depth), replacing rules the
  // previous guard config generated so removals propagate cleanly.
  const prevRules = new Set(genDenyRules(prev));
  const newRules = body.mirrorDeny ? genDenyRules(cfg) : [];
  settings.permissions = settings.permissions || {};
  let deny = settings.permissions.deny || [];
  deny = deny.filter((r) => !prevRules.has(r) || newRules.includes(r));
  for (const r of newRules) if (!deny.includes(r)) deny.push(r);
  if (deny.length) settings.permissions.deny = deny; else delete settings.permissions.deny;

  if (body.forbidBypass) settings.permissions.disableBypassPermissionsMode = 'disable';
  else delete settings.permissions.disableBypassPermissionsMode;
  if (!Object.keys(settings.permissions).length) delete settings.permissions;

  rotateBackups(gp.settingsFile);
  fs.mkdirSync(path.dirname(gp.settingsFile), { recursive: true });
  fs.writeFileSync(gp.settingsFile, JSON.stringify(settings, null, 2) + '\n');

  return { ok: true, hookFile: gp.hookFile, cfgFile: gp.cfgFile, settingsFile: gp.settingsFile, mirrored: newRules.length };
}

function readGuard(scope, dir) {
  const gp = guardPaths(scope, dir);
  const cfg = readJsonSafe(gp.cfgFile) || { files: [], commands: [] };
  const settings = readJsonSafe(gp.settingsFile) || {};
  const denySet = new Set((settings.permissions && settings.permissions.deny) || []);
  const gen = genDenyRules(cfg);
  return {
    files: cfg.files || [],
    commands: cfg.commands || [],
    hookFile: gp.hookFile,
    hookExists: fs.existsSync(gp.hookFile),
    registered: guardIsRegistered(settings),
    mirrorDeny: gen.length > 0 && gen.every((r) => denySet.has(r)),
    forbidBypass: !!(settings.permissions && settings.permissions.disableBypassPermissionsMode === 'disable'),
    settingsFile: gp.settingsFile,
  };
}

// HOOK_SCRIPT is exported for the selftest, which writes it to a temp dir and
// executes it against crafted PreToolUse events.
module.exports = { HOOK_SCRIPT, applyGuard, readGuard };
